disabled_rules:
  - trailing_comma
  - todo

analyzer_rules:
  - explicit_self

opt_in_rules:
  - empty_count
  - let_var_whitespace

line_length:
  warning: 120
  error: 140

file_length:
  warning: 500
  error: 600

type_body_length:
  warning: 400
  error: 500

function_body_length:
  warning: 100
  error: 140

identifier_name:
  min_length:
    warning: 2
    error: 1

excluded:
  - .build
  - node_modules
  - Package.resolved
